//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tiorem.editor.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogueTag
    {
        public CatalogueTag()
        {
            this.ArticleTag = new HashSet<ArticleTag>();
        }
    
        public long Id { get; set; }
        public string TagName { get; set; }
        public Nullable<int> Hits { get; set; }
        public System.DateTime InsertDate { get; set; }
        public int InsertUserId { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<ArticleTag> ArticleTag { get; set; }
        public virtual User User { get; set; }
    }
}
