//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tiorem.editor.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogueSource
    {
        public CatalogueSource()
        {
            this.Article = new HashSet<Article>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public string SourceUrl { get; set; }
        public Nullable<int> Followers { get; set; }
        public bool Active { get; set; }
    
        public virtual ICollection<Article> Article { get; set; }
    }
}
