//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tiorem.editor.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Article = new HashSet<Article>();
            this.CatalogueTag = new HashSet<CatalogueTag>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public bool Active { get; set; }
        public System.DateTime InsertedAt { get; set; }
    
        public virtual ICollection<Article> Article { get; set; }
        public virtual ICollection<CatalogueTag> CatalogueTag { get; set; }
    }
}
