//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tiorem.editor.database
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ARTICLE_SUMMARY
    {
        public long Id { get; set; }
        public string SourceName { get; set; }
        public int SourceId { get; set; }
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> PubDate { get; set; }
        public bool Active { get; set; }
        public bool Approved { get; set; }
        public Nullable<int> ApprovedUserId { get; set; }
        public System.DateTime InsertedAt { get; set; }
        public Nullable<System.DateTime> ApprovedAt { get; set; }
        public string Username { get; set; }
    }
}
